#ifndef BSPLINEMOUSE_GLOBAL_H
#define BSPLINEMOUSE_GLOBAL_H

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#if defined(BSPLINEMOUSE_LIBRARY)
#  define BSPLINEMOUSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define BSPLINEMOUSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BSPLINEMOUSE_GLOBAL_H
